import { useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ArrowUpRight, ExternalLink, Github, BookOpen, X } from 'lucide-react';
import GlassmorphicCard from './GlassmorphicCard';

type Project={id:string;title:string;category:'Mobile'|'Web'|'Game'|'Business';status:string;description:string;tech:string[];endProduct?:string;github?:string;screenshots?:string[];tags:string[]};
const base='https://raw.githubusercontent.com/joshuamussanga7-cpu/sitta-jared-portfolio/main/public/projects';
const img=(name:string)=>`${base}/${encodeURIComponent(name)}`;
const projects:Project[]=[
{id:'university-notes',title:'University Notes',category:'Mobile',status:'LIVE',description:'A student learning ecosystem combining academic resources, past papers, community features and Six AI.',tech:['Flutter','Firebase','AI','Next.js'],tags:['AI','EdTech','Student'],endProduct:'https://webuni.clastarhub.com',screenshots:['University Notes-1.jpg','University Notes-2.jpg','University Notes-3.jpg','University Notes-4.jpg','University Notes-5.jpg','University Notes-6.jpg','University Notes-10.jpg']},
{id:'savi',title:'SAVI',category:'Web',status:'IN DEVELOPMENT',description:'A global digital rewards platform built around tasks, offers, validation, withdrawals and trust.',tech:['Next.js','React','TypeScript','Firebase'],tags:['Rewards','Web','Business'],endProduct:'https://savi.clastarhub.com'},
{id:'uni-connect',title:'Uni Connect',category:'Mobile',status:'IN DEVELOPMENT',description:'A marketplace experience connecting buyers and sellers through listings, discovery and communication.',tech:['Flutter','Firebase','Firestore'],tags:['Marketplace','Commerce','Mobile']},
{id:'uniplanner',title:'UniPlanner',category:'Mobile',status:'ACTIVE',description:'A student productivity system for schedules, exams, tasks, reminders and academic organization.',tech:['Flutter','Firebase','Dart','Provider'],tags:['Productivity','EdTech','Mobile'],screenshots:['Screenshot_20260409_163417_uni planner.jpg','Screenshot_20260409_163426_uni planner.jpg','Screenshot_20260409_163432_uni planner.jpg','Screenshot_20260409_163447_uni planner.jpg']},
{id:'loan-manager',title:'Clastar Microfinance / Loan Manager',category:'Mobile',status:'PRODUCT',description:'A financial-management product for organizing lending workflows, customers and loan operations.',tech:['Flutter','Firebase','Dart'],tags:['FinTech','Loans','Business'],screenshots:['Screenshot_20260409_163231_Loan manager app.jpg','Screenshot_20260409_163302_Loan manager app.jpg','Screenshot_20260409_163319_Loan manager app.jpg','Screenshot_20260409_163329_Loan manager app.jpg']},
{id:'iq-booster',title:'IQ Booster',category:'Game',status:'COMPLETE',description:'An interactive brain-training game focused on thinking, problem solving, memory and player improvement.',tech:['Android','Game Development','UI/UX'],tags:['Game','Education','Android'],github:'https://github.com/joshuamussanga7-cpu/IQ-booster'},
{id:'hoop-shot',title:'Hoop Shot',category:'Game',status:'COMPLETE',description:'A basketball-themed interactive game exploring accessible mobile entertainment and gameplay.',tech:['Android','Game Development','UI/UX'],tags:['Game','Sports','Android'],github:'https://github.com/joshuamussanga7-cpu/hoop-shot'},
{id:'stack-hop',title:'Stack Hop',category:'Game',status:'COMPLETE',description:'A casual game project exploring simple gameplay, interaction and iterative product development.',tech:['Android','Game Development','UI/UX'],tags:['Game','Casual','Android'],github:'https://github.com/joshuamussanga7-cpu/stack-hop1'},
{id:'mayra-tour',title:'MAYRA TOUR',category:'Business',status:'LIVE',description:'A tourism-focused digital presence for presenting travel services and a professional travel brand.',tech:['React','Web Development','Responsive UI'],tags:['Travel','Business','Web'],endProduct:'https://mayra-tours.vercel.app'},
{id:'kaymex',title:'KAYMEX COMPANY LIMITED',category:'Business',status:'LIVE',description:'A corporate digital presence designed around professional business identity and service presentation.',tech:['React','Web Development','Responsive UI'],tags:['Corporate','Business','Web'],endProduct:'https://kaymex-company-limited.vercel.app'},
{id:'kaya-homes',title:'KAYA HOMES LIMITED',category:'Business',status:'LIVE',description:'A property-focused digital experience for presenting a real-estate and housing brand online.',tech:['React','Web Development','Responsive UI'],tags:['Real Estate','Business','Web'],endProduct:'https://kaya-homes-limited.vercel.app'},
{id:'red-apple',title:'Red Apple Events & Decor',category:'Business',status:'IN DEVELOPMENT',description:'A visual business website for an events and decoration-focused brand.',tech:['React','Web Development','Responsive UI'],tags:['Events','Business','Web']},
];
const posts=[
['Building SAVI: From Product Idea to a Real Web Platform','SAVI','building-savi-web-platform'],['Building University Notes with AI','University Notes','building-university-notes-with-ai'],['Building Stack Hop','Stack Hop','building-stack-hop'],['Designing Hoop Shot','Hoop Shot','designing-hoop-shot'],['How I Built IQ Booster','IQ Booster','how-i-built-iq-booster'],['From Idea to Production Web App','ClastarHub','from-idea-to-production-web-app'],['Firebase for Real-World Apps','Technology','firebase-for-real-world-apps'],['Flutter vs Next.js: Product Decisions','Technology','flutter-vs-nextjs-product-decisions'],['How to Build a Game UI','Games','how-to-build-a-game-ui'],['Optimizing Mobile Games for Low-End Devices','Games','optimizing-mobile-games-for-low-end-devices'],['Responsive Web Design','Technology','responsive-web-design']
];

export default function CompanyPortfolio(){
 const [filter,setFilter]=useState('All'); const [selected,setSelected]=useState<Project|null>(null);
 const filtered=useMemo(()=>filter==='All'?projects:projects.filter(p=>p.category===filter),[filter]);
 return <section id="portfolio" className="section-pad">
  <div className="container">
   <div className="section-head"><div><p className="section-kicker">08 / COMPANY PORTFOLIO</p><h2>Our work.<br/><span>Our products.</span></h2></div><p>Every project is presented as a ClastarHub company product, with visual evidence and a direct path to the end product.</p></div>
   <div className="filter-row">{['All','Mobile','Web','Game','Business'].map(item=><button key={item} className={`filter-chip ${filter===item?'active':''}`} onClick={()=>setFilter(item)}>{item}</button>)}</div>
   <div className="company-work-grid">{filtered.map((p,i)=><motion.div key={p.id} initial={{opacity:0,y:24}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{delay:i*.04}}><GlassmorphicCard className="company-card" hover><button type="button" onClick={()=>setSelected(p)} className="company-card-inner" style={{border:0,padding:0,width:'100%',textAlign:'left',cursor:'pointer',background:'transparent'}}><div className="company-visual">{p.screenshots?.[0]?<img src={img(p.screenshots[0])} alt={p.title} loading="lazy"/>:<div className="work-window"><div className="window-bar"><i/><i/><i/></div><div className="window-lines"><b/><b/><b/></div><div className="window-block"/></div>}<div className="company-overlay"/><div className="company-badges"><span className="glass-badge">{p.category}</span><span className="glass-badge">{p.status}</span></div><div className="company-caption"><small>CLASTAR HUB PRODUCT</small><h3>{p.title}</h3></div></div><div className="company-info"><p>{p.description}</p><div className="tag-row">{p.tags.map(t=><span key={t}>{t}</span>)}</div><div className="company-footer"><b>{p.endProduct?'END PRODUCT AVAILABLE':p.github?'SOURCE AVAILABLE':'PRODUCT DETAILS'}</b><ArrowUpRight size={16}/></div></div></button></GlassmorphicCard></motion.div>)}</div>
   <div id="insights" style={{marginTop:120}}><div className="section-head"><div><p className="section-kicker">09 / INSIGHTS</p><h2>Build logs.<br/><span>Ideas & lessons.</span></h2></div><p>Engineering stories from the company ecosystem, connected to the products they describe.</p></div><div className="insights-grid">{posts.map(([title,related,slug],i)=><a key={slug} href={`https://github.com/joshuamussanga7-cpu/clastarhub/blob/main/content/blog/${slug}.md`} target="_blank" rel="noreferrer"><GlassmorphicCard className="insight-card"><small>CLASTARHUB · {related}</small><h3>{title}</h3><p>Company engineering insight connected to the related product.</p><div className="insight-arrow"><BookOpen size={16}/></div></GlassmorphicCard></a>)}</div></div>
  </div>
  <AnimatePresence>{selected&&<motion.div className="project-overlay" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onClick={()=>setSelected(null)}><motion.div className="project-modal" initial={{y:35,opacity:0,scale:.98}} animate={{y:0,opacity:1,scale:1}} onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="Close"><X/></button><p className="section-kicker">CLASTARHUB · {selected.category} · {selected.status}</p><h2>{selected.title}</h2><p className="modal-description">{selected.description}</p><div className="modal-meta"><div><small>PLATFORM</small><strong>{selected.category}</strong></div><div><small>TECHNOLOGY</small><strong>{selected.tech.join(' · ')}</strong></div></div><div className="modal-features"><div>{selected.tags.map(t=><span key={t}>{t}</span>)}</div></div>{selected.screenshots?.length?<div className="modal-gallery">{selected.screenshots.map(s=><img key={s} src={img(s)} alt={`${selected.title} screenshot`} loading="lazy"/>)}</div>:null}<div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{selected.endProduct&&<a className="primary-cta" href={selected.endProduct} target="_blank" rel="noreferrer">Open end product <ExternalLink size={17}/></a>}{selected.github&&<a className="primary-cta" href={selected.github} target="_blank" rel="noreferrer">View source <Github size={17}/></a>}{!selected.endProduct&&!selected.github&&<span className="glass-badge">Launch link pending</span>}</div></motion.div></motion.div>}</AnimatePresence>
 </section>;
}
