import { motion } from 'framer-motion';
import { ArrowRight, ArrowUpRight, BrainCircuit, Building2, Layers3, Menu, Rocket, Sparkles, X, Zap, type LucideIcon } from 'lucide-react';
import { useState } from 'react';

type Product = [string, string, string, string, string];
type Destination = { title: string; desc: string; Icon: LucideIcon; href: string };

const products: Product[] = [
  ['University Notes','DIGITAL PRODUCT','Learning ecosystem combining study resources, community and AI.','LIVE · WEB + ANDROID','https://webuni.clastarhub.com'],
  ['SAVI','PRODUCT · IN DEVELOPMENT','Student platform built around tasks, rewards, validation and trusted workflows.','IN DEVELOPMENT · WEB + MOBILE','#contact'],
  ['KAYMEX','DIGITAL SOLUTION','Corporate web experience designed around clarity and credibility.','SELECTED WORK · WEB','#solutions'],
];
const destinations: Destination[] = [
  { title:'Products', desc:'Software products built for people, workflows and everyday problems.', Icon:Rocket, href:'#products' },
  { title:'Solutions', desc:'Websites, business systems and connected experiences built around real needs.', Icon:Building2, href:'#solutions' },
  { title:'Technology', desc:'AI, engineering and experiments that push the ecosystem forward.', Icon:BrainCircuit, href:'#technology' },
];
const solutions = ['Digital products','Business systems','Web & mobile','AI & automation'];
const technology = ['AI assistants','Document intelligence','Automation','Cloud-connected workflows'];
const lab = ['IQ Booster','Stack Hop','Hoop Shot','FanSport Race'];

export default function ClastarCompanyHome(){
 const [open,setOpen]=useState(false);
 const go=(id:string)=>{if(id.startsWith('#'))document.querySelector(id)?.scrollIntoView({behavior:'smooth'});setOpen(false)};
 return <div className="clastar-v2">
  <header className="v2-nav"><a className="v2-brand" href="#home"><span className="brand-mark">C</span><span>CLASTAR<span>HUB</span></span></a><nav className="v2-nav-links"><button onClick={()=>go('#products')}>Products</button><button onClick={()=>go('#solutions')}>Solutions</button><button onClick={()=>go('#technology')}>Technology</button><button onClick={()=>go('#company')}>Company</button><button onClick={()=>go('#resources')}>Resources</button></nav><div className="v2-nav-actions"><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X size={20}/>:<Menu size={20}/>}</button><button className="nav-cta" onClick={()=>go('#contact')}>Contact <ArrowUpRight size={16}/></button></div></header>
  {open&&<div className="v2-mobile-menu">{[['Products','#products'],['Solutions','#solutions'],['Technology','#technology'],['Company','#company'],['Resources','#resources'],['Contact','#contact']].map(([n,h])=><button key={h} onClick={()=>go(h)}>{n}</button>)}</div>}
  <main>
   <section id="home" className="v2-hero"><div className="v2-hero-grid"/><div className="v2-hero-glow v2-glow-a"/><div className="v2-hero-glow v2-glow-b"/><motion.div className="v2-orbit" animate={{y:[0,-14,0],rotate:[0,8,0]}} transition={{duration:9,repeat:Infinity,ease:'easeInOut'}}><div className="orbit-core"><Sparkles size={24}/></div><div className="orbit-line orbit-line-1"/><div className="orbit-line orbit-line-2"/><div className="orbit-line orbit-line-3"/></motion.div><div className="v2-container v2-hero-inner"><div className="v2-eyebrow"><span className="eyebrow-dot"/> CLASTARHUB · TECHNOLOGY COMPANY</div><motion.h1 initial={{opacity:0,y:25}} animate={{opacity:1,y:0}}>We build technology<br/><em>for what comes next.</em></motion.h1><p className="v2-hero-copy">ClastarHub creates digital products, intelligent systems and technology experiences designed to solve real problems and create new possibilities.</p><div className="v2-hero-actions"><button className="v2-primary" onClick={()=>go('#products')}>Explore our products <ArrowRight size={18}/></button><button className="v2-secondary" onClick={()=>go('#contact')}>Work with us <ArrowUpRight size={18}/></button></div><div className="v2-stat-row"><div className="v2-stat"><strong>3</strong><span>featured products</span></div><div className="v2-stat"><strong>4</strong><span>technology disciplines</span></div><div className="v2-stat"><strong>1</strong><span>connected ecosystem</span></div></div></div></section>
   <section id="about" className="v2-section v2-destinations"><div className="v2-container"><div className="v2-section-intro"><div><span className="v2-kicker">01 / WHAT IS CLASTARHUB?</span><h2>An ecosystem of<br/><span>products, solutions and technology.</span></h2></div><p>We build across three connected areas: useful products, real-world solutions and emerging technology turned into practical experiences.</p></div><div className="v2-destination-grid">{destinations.map((item,i)=>{const Icon=item.Icon;return <motion.button key={item.title} className="v2-destination-card accent-blue" onClick={()=>go(item.href)} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.07}}><span className="card-number">0{i+1}</span><div className="card-icon"><Icon size={22}/></div><div className="card-copy"><h3>{item.title}</h3><p>{item.desc}</p></div><span className="card-link">Explore <ArrowUpRight size={16}/></span></motion.button>})}</div></div></section>
   <section id="products" className="v2-section v2-featured"><div className="v2-container"><div className="v2-section-intro compact"><div><span className="v2-kicker">02 / PRODUCTS</span><h2>Selected products<br/><span>we've built.</span></h2></div><p>The homepage shows only the strongest examples. Detailed product experiences will live on dedicated pages.</p></div><div className="v2-featured-grid">{products.map((p,i)=><motion.a key={p[0]} className="v2-project-card project-blue" href={p[4]} target={p[4].startsWith('http')?'_blank':undefined} rel={p[4].startsWith('http')?'noreferrer':undefined} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.06}}><div className="project-visual visual-education"><div className="visual-window"><div className="visual-top"><i/><i/><i/></div><div className="visual-content"><div className="visual-pill"/><div className="visual-bars"><b/><b/><b/><b/></div><div className="visual-panel"/></div></div></div><div className="project-body"><span className="project-type">{p[1]}</span><h3>{p[0]}</h3><p>{p[2]}</p><div className="project-footer"><span>{p[3]}</span><ArrowUpRight size={17}/></div></div></motion.a>)}</div></div></section>
   <section id="solutions" className="v2-section v2-split-section"><div className="v2-container"><div className="v2-split-card"><div className="v2-split-copy"><span className="v2-kicker">03 / SOLUTIONS</span><h2>Technology that fits<br/><span>the real world.</span></h2><p>From first idea to a working system, we design and build digital experiences around how people and organizations actually work.</p><button className="v2-secondary dark" onClick={()=>go('#contact')}>Start a project <ArrowRight size={18}/></button></div><div className="v2-list-panel">{solutions.map((x,i)=><div className="v2-list-row" key={x}><span>0{i+1}</span><strong>{x}</strong><ArrowUpRight size={16}/></div>)}</div></div></div></section>
   <section id="technology" className="v2-section v2-tech-section"><div className="v2-container"><div className="v2-section-intro compact"><div><span className="v2-kicker">04 / TECHNOLOGY</span><h2>AI is a capability.<br/><span>Purpose comes first.</span></h2></div><p>We apply AI and emerging technology where it makes products smarter, faster, more accessible or more useful.</p></div><div className="v2-tech-grid">{technology.map((x,i)=><div className="v2-tech-chip" key={x}><span>0{i+1}</span><strong>{x}</strong><Zap size={15}/></div>)}</div></div></section>
   <section id="process" className="v2-section v2-company"><div className="v2-container"><div className="v2-company-grid"><div><span className="v2-kicker">05 / HOW WE BUILD</span><h2>From idea<br/><span>to impact.</span></h2></div><div><div className="v2-tech-grid">{['Discover','Design','Build','Launch','Evolve'].map((x,i)=><div className="v2-tech-chip" key={x}><span>0{i+1}</span><strong>{x}</strong><CheckIcon/></div>)}</div><p className="muted">A focused process keeps strategy, design, engineering and iteration connected.</p></div></div></div></section>
   <section id="work" className="v2-section v2-featured"><div className="v2-container"><div className="v2-section-intro compact"><div><span className="v2-kicker">06 / CASE STUDIES</span><h2>Show the work.<br/><span>Then show the outcome.</span></h2></div><p>Dedicated case studies will document challenge, approach, technology and result instead of turning the homepage into a project database.</p></div><div className="v2-featured-grid"><article className="v2-project-card project-blue"><div className="project-body"><span className="project-type">EDUCATION · CASE STUDY</span><h3>University Notes</h3><p>From a student notes concept to a connected learning ecosystem with web, mobile and AI capabilities.</p><div className="project-footer"><span>CHALLENGE · APPROACH · RESULT</span><ArrowUpRight size={17}/></div></div></article><article className="v2-project-card project-blue"><div className="project-body"><span className="project-type">BUSINESS · CASE STUDY</span><h3>KAYMEX</h3><p>A focused digital presence built around clarity, credibility and a serious industrial identity.</p><div className="project-footer"><span>BRAND · EXPERIENCE · DELIVERY</span><ArrowUpRight size={17}/></div></div></article></div></div></section>
   <section id="lab" className="v2-section v2-lab-section"><div className="v2-container"><div className="v2-lab-head"><div><span className="v2-kicker">07 / CLASTARHUB LAB</span><h2>We experiment<br/><span>to learn faster.</span></h2></div><p>Interactive builds let us explore interaction, performance and playful technology without pretending every experiment is a product.</p></div><div className="v2-lab-grid">{lab.map((x,i)=><div className="v2-lab-card" key={x}><div className="lab-index">0{i+1}</div><div className="lab-orb"><Layers3 size={21}/></div><div><span>INTERACTIVE</span><h3>{x}</h3></div><b>COMPLETE</b></div>)}</div></div></section>
   <section id="company" className="v2-section v2-investment"><div className="v2-container"><div className="v2-investment-card"><div><span className="v2-kicker">08 / COMPANY</span><h2>Not just projects.<br/><span>A technology company.</span></h2><p>ClastarHub is an ecosystem for products, solutions, experiments and ventures. Some ideas become software. Some become businesses. Some become lessons that shape what we build next.</p></div><button className="v2-primary" onClick={()=>go('#contact')}>About ClastarHub <ArrowRight size={18}/></button></div></div></section>
   <section id="resources" className="v2-section v2-company"><div className="v2-container"><div className="v2-company-grid"><div><span className="v2-kicker">09 / RESOURCES</span><h2>Ideas behind<br/><span>the builds.</span></h2></div><div><p>Insights, build logs, news and technical stories will grow into the company's knowledge layer.</p><div className="v2-tech-grid"><div className="v2-tech-chip"><span>01</span><strong>Insights</strong><ArrowUpRight size={15}/></div><div className="v2-tech-chip"><span>02</span><strong>Build logs</strong><ArrowUpRight size={15}/></div><div className="v2-tech-chip"><span>03</span><strong>News</strong><ArrowUpRight size={15}/></div></div></div></div></div></section>
   <section id="contact" className="v2-section v2-contact"><div className="v2-container"><div className="v2-contact-card"><div><span className="v2-kicker">10 / CONTACT</span><h2>Let's build what<br/><span>comes next.</span></h2><p>Bring us the idea, problem or opportunity. We'll start from there.</p></div><a className="v2-primary" href="mailto:hello@clastarhub.com">Start a conversation <ArrowUpRight size={18}/></a></div></div></section>
  </main>
  <footer className="v2-footer"><div className="v2-container v2-footer-inner"><div><a href="#home" className="v2-footer-brand">CLASTAR<span>HUB</span></a><p>Building technology for what comes next.</p></div><div><strong>Explore</strong><span>Products · Solutions · Technology</span></div><div><strong>Company</strong><span>About · Resources · Contact</span></div><div><strong>Legal</strong><span>Privacy · Terms · Cookies</span></div><span>© 2026 ClastarHub</span></div></footer>
 </div>
}
function CheckIcon(){return <span aria-hidden="true" style={{fontSize:12}}>✓</span>}
