import { ArrowLeft, ArrowUpRight, Bot, BrainCircuit, Cloud, Code2, Database, Layers3, Sparkles, Workflow } from 'lucide-react'

const solutions = [
  ['Digital Products','Turn an idea into a focused product with clear user journeys, strong interfaces and an architecture that can grow.','Product strategy','UX & UI','Web & mobile'],
  ['Business Systems','Replace fragmented workflows with connected software designed around how a business actually operates.','Workflow design','Dashboards & portals','Data-driven systems'],
  ['Web & Mobile','Build fast, responsive experiences that feel polished on every screen and connect cleanly to the services behind them.','Web applications','Mobile experiences','Cloud integration'],
  ['AI Solutions','Add useful intelligence to products and operations through assistants, document understanding, automation and AI-powered workflows.','AI assistants','Document intelligence','Automation'],
]

const technology = [
  { title:'AI & Intelligence', desc:'Practical AI capabilities embedded where they create real utility—not AI for decoration.', Icon:BrainCircuit },
  { title:'Engineering', desc:'Modern frontend, backend and product engineering focused on reliability, speed and maintainability.', Icon:Code2 },
  { title:'Cloud & Data', desc:'Connected infrastructure and data workflows that let products scale beyond the interface.', Icon:Cloud },
  { title:'Automation', desc:'Systems that reduce repetitive work by connecting actions, services and intelligent decision points.', Icon:Workflow },
]

function Shell({ children }: { children: React.ReactNode }) { return <main className="clastar-st-page"><header className="st-nav"><a href="/" className="product-brand">CLASTARHUB</a><a href="/" className="product-back"><ArrowLeft size={16}/> Back to ClastarHub</a></header>{children}<footer className="st-footer"><span>CLASTARHUB</span><a href="/#contact">Start a conversation <ArrowUpRight size={14}/></a></footer></main> }

export function ClastarSolutions() { return <Shell><section className="st-hero"><span className="v2-kicker">SOLUTIONS</span><h1>Technology shaped around <em>the problem.</em></h1><p>We design and build digital products, business systems and AI-enabled experiences around real goals—not generic templates.</p></section><section className="st-solution-list">{solutions.map(([title,desc,...items],i)=><article className="st-solution" key={title}><div className="st-number">0{i+1}</div><div><h2>{title}</h2><p>{desc}</p></div><div className="st-tags">{items.map(x=><span key={x}>{x}</span>)}</div><ArrowUpRight className="st-arrow" size={20}/></article>)}</section><section className="st-process"><span className="v2-kicker">OUR APPROACH</span><h2>Start with the problem.<br/>Build the right system.</h2><div className="st-process-grid">{['Discover','Design','Engineer','Evolve'].map((x,i)=><div key={x}><b>0{i+1}</b><h3>{x}</h3><p>Focused decisions at every stage, with room to learn and improve.</p></div>)}</div></section><section className="st-cta"><Sparkles size={22}/><h2>Have a system in mind?</h2><a className="v2-btn v2-btn-primary" href="/#contact">Let's build it <ArrowUpRight size={16}/></a></section></Shell> }

export function ClastarTechnology() { return <Shell><section className="st-hero"><span className="v2-kicker">TECHNOLOGY</span><h1>The intelligence and engineering behind <em>what we build.</em></h1><p>Our technology layer brings together software engineering, AI, cloud systems and automation to turn ideas into useful experiences.</p></section><section className="st-tech-grid">{technology.map(({title,desc,Icon})=><article className="st-tech" key={title}><div className="st-tech-icon"><Icon size={23}/></div><h2>{title}</h2><p>{desc}</p><ArrowUpRight size={18}/></article>)}</section><section className="st-tech-showcase"><div className="st-tech-orb"><BrainCircuit size={44}/></div><div><span className="v2-kicker">CLASTARHUB LAB</span><h2>We experiment before we standardize.</h2><p>Experiments, prototypes and internal builds help us test ideas quickly, discover useful patterns and bring the strongest ones into products.</p><a className="v2-btn v2-btn-secondary" href="/#technology">Explore the lab <ArrowUpRight size={16}/></a></div></section><section className="st-capabilities"><span className="v2-kicker">CAPABILITY STACK</span><div className="st-stack"><span><Database size={15}/> Data</span><span><Layers3 size={15}/> Cloud</span><span><Bot size={15}/> AI</span><span><Code2 size={15}/> Software</span></div></section><section className="st-cta"><h2>Let's put technology to work.</h2><a className="v2-btn v2-btn-primary" href="/#contact">Talk to ClastarHub <ArrowUpRight size={16}/></a></section></Shell> }

export default function ClastarSolutionsTechnology() { const path=window.location.pathname.replace(/\/+$/,''); return path==='/technology'||path.startsWith('/technology/') ? <ClastarTechnology/> : <ClastarSolutions/> }
